from mysql.connector import connect, Error
from hashlib import sha256


def db_func():
    u = input('Введите логин mysql: ')
    p = input('Пароль: ')
    db = connect(
        host="localhost",
        port=3306,
        user=u,
        password=p
    )
    c = db.cursor()
    c.execute('DROP DATABASE IF EXISTS users')
    c.execute('CREATE DATABASE users')
    c.execute('USE users')
    c.execute('DROP TABLE IF EXISTS `log`')
    c.execute("""CREATE TABLE `log`(id SERIAL PRIMARY KEY,
     login VARCHAR(100) UNIQUE,
     password VARCHAR(250),
     created_at DATETIME DEFAULT NOW()
     )
     """)
    l = input('Создание нового пользователя введите логин: ')
    p = input("Создание пароля введите пароль: ")
    cp = sha256(p.encode() + l.encode()).hexdigest()
    print(f'Хеш - {cp}')
    c.execute(f'INSERT INTO `log`(login, password) VALUES ("{l}", "{cp}")')
    db.commit()
    c.execute('SELECT password FROM `log`')
    rows = c.fetchall()
    repeat = input('Подтверждение пароля: ')
    repeat_pass = sha256(repeat.encode() + l.encode()).hexdigest()
    for i in rows:
        if i[0] == repeat_pass:
            return 'Welcome'
        else:
            return 'Password is not correct'


print(db_func())
